'use strict';
const $=id=>document.getElementById(id);
const labels={RECEBIDO:['Na fila','Seu plano foi recebido e aguarda processamento.'],EM_PROCESSAMENTO:['Em análise','A auditoria está verificando o plano e preparando o relatório.'],CONCLUIDO_SEM_ACHADOS:['Concluída sem achados','Nenhum achado nas verificações executadas. Confira a cobertura abaixo.'],CONCLUIDO_COM_ACHADOS:['Concluída com pontos para revisão','Veja os itens abaixo e confira as células indicadas no plano.'],INCONCLUSIVO:['Análise parcial','Há resultados disponíveis, mas faltam informações para uma conclusão completa.'],ERRO_TECNICO:['Processamento interrompido','O envio continua registrado. A equipe precisa conferir a ocorrência antes de retomar.']};
let credentials=null, result=null, busy=false, timer=null, generation=0, attempts=0;
let endpoint=null;
try{const u=new URL(window.MEDIA_UPLOAD_CONFIG?.statusEndpoint);if(u.protocol==='https:'&&u.hostname==='pingadomidia.app.n8n.cloud'&&u.pathname==='/webhook/consultar-auditoria-sicoob'&&!u.search&&!u.hash&&!u.username&&!u.password)endpoint=u.href;}catch{}
const idPattern=/^AUD-[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i;
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
function message(s){$('message').textContent=s;$('message').hidden=!s;}
function element(tag,text,className){const el=document.createElement(tag);el.textContent=text;if(className)el.className=className;return el;}
function summary(meta){const list=$('plan-summary');list.replaceChildren();for(const [k,l] of [['cliente','Cliente'],['campanha','Campanha'],['nome_arquivo','Arquivo'],['versao_plano','Versão do plano'],['revisao_plano','Revisão do plano'],['data_ultima_revisao','Última revisão'],['versao_gabarito','Gabarito aplicado']]){const g=document.createElement('div');g.append(element('dt',l),element('dd',meta?.[k]||'Não informado'));list.append(g);}}
function findingTitle(a){const map={TOTAL_DIVERGENTE:'Total divergente',FORMULA_TOTAL_INADEQUADA:'Fórmula do total',FORMULA_INADEQUADA:'Fórmula inadequada',CAMPO_AUSENTE:'Campo ausente',VALOR_DIVERGENTE:'Valor divergente'};return map[a.tipo_achado||a.tipo]||'Ponto para revisão';}
function findingValue(...values){for(const value of values){if((typeof value==='string'||typeof value==='number')&&String(value).trim()!=='')return String(value).trim();}return '';}
function findingAction(a){
 const cell=findingValue(a.celula),sheet=findingValue(a.aba);
 const column=findingValue(a.coluna)||(cell.match(/^\$?([A-Z]+)\$?\d+$/i)?.[1]||'');
 const field=findingValue(a.campo_canonico,a.campo);
 const location=[sheet?`na aba ${sheet}`:'no plano',column?`coluna ${column}`:'',cell?`célula ${cell}`:(a.linha?`linha ${a.linha}`:''),!column&&field?`campo ${field}`:''].filter(Boolean).join(', ');
 const expected=findingValue(a.esperado,a.valor_correto);
 const tipo=a.tipo_achado||a.tipo;
 const verb=tipo==='CAMPO_AUSENTE'?'Preencha o campo indicado':(tipo==='FORMULA_TOTAL_INADEQUADA'||tipo==='FORMULA_INADEQUADA'?'Confira a fórmula':'Confira o valor');
 return `${verb} ${location}. ${expected?`Resultado esperado: ${expected}.`:'O resultado esperado não foi informado pela auditoria; confira os dados de origem antes de alterar.'}`;
}
function findings(){const list=$('findings');list.replaceChildren();const all=Array.isArray(result?.detalhes)?result.detalhes:[];const q=norm($('search').value),severity=$('severity').value;const filtered=all.filter(a=>(!severity||norm(a.severidade).startsWith(severity))&&(!q||norm([a.veiculo,a.aba,a.campo,a.campo_canonico,a.id_regra,a.descricao,a.kpi,a.tipo_compra].join(' ')).includes(q)));
 $('detail-count').textContent=filtered.length+' de '+all.length+' itens exibidos'+(result?.detalhes_truncados?' · lista parcial; consulte o Word.':'.');
 if(!all.length){list.append(element('p',result?.finalizado?'Nenhum detalhe disponível nesta consulta. Confira o Word e a cobertura antes de interpretar o resultado.':'Os detalhes aparecerão após o processamento.'));return;}
 for(const a of filtered){const card=element('article','', 'finding-card');card.append(element('span',[a.severidade,findingTitle(a)].filter(Boolean).join(' · '),'finding-tag'),element('h4',a.veiculo||a.campo_canonico||a.campo||'Item para revisão'),element('p',[a.aba,a.celula?('célula '+a.celula):(a.linha?'linha '+a.linha:''),a.tipo_compra,a.kpi].filter(Boolean).join(' · '),'finding-location'));
  const found=findingValue(a.encontrado,a.valor_atual), expected=findingValue(a.esperado,a.valor_correto);
  const what=element('div','', 'finding-explanation');what.append(element('strong','O que foi encontrado'),element('p',a.descricao||((found||expected)?`Encontrado: ${found||'não informado'} · Esperado: ${expected||'não informado'}`:'Confira o item indicado no plano.')));card.append(what);
  const how=element('div','', 'finding-explanation finding-action');how.append(element('strong','Como corrigir'),element('p',findingAction(a)));card.append(how);list.append(card);}
}
function coverage(){const root=$('coverage');root.replaceChildren();const r=result?.resumo||{};root.append(element('p','Resumo mensal: '+(r.mensal?.status||'Consulte o relatório.')));for(const a of r.mensal?.divergencias||[])root.append(element('p','Divergência de valor: '+(a.descricao||a.motivo||JSON.stringify(a))));for(const a of r.mensal?.avisos||[])root.append(element('p','Aviso: '+(a.descricao||a.motivo||JSON.stringify(a))));for(const a of r.avisos||[])root.append(element('p',String(a)));if(result?.detalhes_disponiveis===false)root.append(element('p','Os detalhes não puderam ser carregados agora. Tente atualizar ou consulte o Word.'));}
function render(data){result=data;$('access-panel').hidden=true;$('result').hidden=false;const label=labels[data.status_auditoria];$('status-label').textContent=label[0];$('status-detail').textContent=label[1];$('result-id').textContent=data.id_auditoria;summary(data.meta);$('finding-count').textContent=data.qtd_achados??'—';$('pending-count').textContent=data.qtd_pendencias??'—';$('download').hidden=!data.documento_disponivel;findings();coverage();}
async function request(download=false){if(!endpoint||!credentials)throw Error('Consulta indisponível.');const abort=new AbortController(),t=setTimeout(()=>abort.abort(),45000);try{const response=await fetch(endpoint,{method:'POST',body:new URLSearchParams({...credentials,baixar:String(download)}),credentials:'omit',redirect:'error',cache:'no-store',referrerPolicy:'no-referrer',signal:abort.signal});if(response.status===404)throw Error('Auditoria não encontrada ou chave inválida. Confira o e-mail de confirmação.');if(!response.ok)throw Error('Consulta temporariamente indisponível. Tente novamente em instantes.');const data=await response.json();if(data.disponivel!==true||data.id_auditoria!==credentials.id_auditoria||!labels[data.status_auditoria])throw Error('Resposta inválida. Tente atualizar novamente.');return data;}finally{clearTimeout(t);}}
function lock(value){busy=value;for(const id of ['consult','refresh','download'])$(id).disabled=value;}
async function refresh(){if(busy)return;clearTimeout(timer);const g=generation;lock(true);message('');try{const data=await request();if(g!==generation)return;render(data);if(!data.finalizado&&attempts++<40)timer=setTimeout(refresh,15000);}catch(e){if(g===generation)message(e.name==='AbortError'?'A consulta demorou mais que o esperado. Tente atualizar.':e.message);}finally{lock(false);}}
$('access-form').addEventListener('submit',e=>{e.preventDefault();if(busy)return;const id=$('audit-id').value.trim(),key=$('access-key').value.trim().toLowerCase();if(!idPattern.test(id)||!/^[a-f0-9]{64}$/.test(key)){message('Confira o identificador e a chave de 64 caracteres recebida por e-mail.');return;}credentials={id_auditoria:id,chave_acesso:key};$('access-key').value='';generation++;attempts=0;refresh();});
$('refresh').addEventListener('click',()=>{attempts=0;refresh();});$('search').addEventListener('input',findings);$('severity').addEventListener('change',findings);
$('exit').addEventListener('click',()=>{generation++;clearTimeout(timer);credentials=null;result=null;$('result').hidden=true;$('access-panel').hidden=false;$('findings').replaceChildren();$('plan-summary').replaceChildren();$('coverage').replaceChildren();$('access-key').value='';message('Consulta encerrada.');});
$('download').addEventListener('click',async()=>{if(busy)return;const g=generation;lock(true);message('');try{const data=await request(true);if(g!==generation)return;const doc=data.documento;if(!doc||doc.mime!=='application/vnd.openxmlformats-officedocument.wordprocessingml.document'||typeof doc.base64!=='string')throw Error('Documento indisponível. Tente novamente.');const raw=atob(doc.base64),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));if(bytes.length<100||bytes[0]!==80||bytes[1]!==75||bytes[2]!==3||bytes[3]!==4)throw Error('Documento inválido. Fale com a equipe responsável.');const url=URL.createObjectURL(new Blob([bytes],{type:doc.mime})),a=document.createElement('a');a.href=url;a.download='Auditoria_'+credentials.id_auditoria+'.docx';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);message('Download solicitado. Confira os downloads do navegador.');}catch(e){if(g===generation)message(e.name==='AbortError'?'O download demorou mais que o esperado. Tente novamente.':e.message);}finally{lock(false);}});
const hash=new URLSearchParams(location.hash.slice(1)),id=hash.get('id')||'',key=hash.get('chave')||'';
history.replaceState(null,'',location.pathname+location.search);
if(idPattern.test(id))$('audit-id').value=id;if(/^[a-f0-9]{64}$/i.test(key)){$('access-key').value=key;if(idPattern.test(id))$('access-form').requestSubmit();}
window.addEventListener('pagehide',()=>{generation++;credentials=null;clearTimeout(timer);});
